basePath: /api
definitions:
  contract.RegisterProducerOptions:
    properties:
      udp_options:
        $ref: '#/definitions/model.UdpOptions'
    type: object
  handler.InitDownloadRequest:
    properties:
      client_udp_options:
        $ref: '#/definitions/model.UdpOptions'
      id:
        type: string
    type: object
  handler.RegisterFileRequest:
    properties:
      name:
        type: string
      producer_id:
        type: string
      size:
        type: integer
    type: object
  model.UdpOptions:
    properties:
      external_ip:
        type: string
      external_port:
        type: integer
    type: object
info:
  contact: {}
  description: API for UDPie file transfer signaller service
  title: UDPie Signaller API
  version: "1.0"
paths:
  /files:
    post:
      consumes:
      - application/json
      description: Register a new file with metadata and associate it with a producer
      parameters:
      - description: File registration request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.RegisterFileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success response with file ID
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request body
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Register a new file
      tags:
      - files
  /initDownload:
    post:
      consumes:
      - application/json
      parameters:
      - description: Init download request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.InitDownloadRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success response with transfer ID
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request body
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Init download
      tags:
      - download
  /producers:
    post:
      consumes:
      - application/json
      description: Register a new producer with UDP options for file transfer
      parameters:
      - description: Producer registration options
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/contract.RegisterProducerOptions'
      produces:
      - application/json
      responses:
        "200":
          description: Success response with producer ID
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request body
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Register a new producer
      tags:
      - producers
  /ws:
    get:
      description: Establishes a WebSocket connection for a producer to receive transfer
        notifications
      parameters:
      - description: Producer ID
        in: query
        name: producer_id
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols
        "400":
          description: Invalid producer ID
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: WebSocket connection for producers
      tags:
      - websocket
schemes:
- http
- https
swagger: "2.0"
